### ISSUE TITLE
storybook 생성

### ISSUE THREAD

**Issue by dawncoding** [Stendhalsynd/career-up-front#36]
## Description
Logo, Picture, Header, Login, Signup component storybook 생성

## Todo
- [x] Logo storybook
- [x] Picture storybook
- [x] Header storybook
- [ ] Login storybook
- [ ] Signup storybook

## ETC
기타사항

## References
- [storybook docs](https://storybook.js.org/docs/react/get-started/install/)

**Comment by Stendhalsynd** [comment]
오.. 스토리북이 많이 추가되었네요
저건 main 에 머지가 된 부분일까요?

**Comment by dawncoding** [comment]
아니요..! 지훈님꺼 merge 받고 나서 하려고 했는데 아직 merge를 안 받았습니다
